//! The bundled themes and what rustpress builds from them.
//!
//! The color themes are vpkit's (`node_modules/vpkit/themes`, an npm
//! `file:` dependency on ../vpkit), embedded into the binary. vpkit's own
//! test (test/themes.mjs) holds each to the design contract and the WCAG
//! minimums; here: the docs site's theme gallery must list exactly the
//! embedded set, with card data taken from the files.

use std::path::PathBuf;

fn repo(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn read(rel: &str) -> String {
    let path = repo(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e} (npm install)"))
}

struct Block {
    selector: String,
    declarations: Vec<(String, String)>,
}

/// Parse a stylesheet into top-level `selector { decl; decl; }` blocks,
/// comments stripped. Theme files are flat, which is all this needs to read.
fn parse_blocks(css: &str) -> Vec<Block> {
    let css = strip_comments(css);
    let mut blocks = Vec::new();
    let mut rest = css.as_str();
    while let Some(open) = rest.find('{') {
        let selector = rest[..open]
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        let mut depth = 1;
        let mut close = open + 1;
        let bytes = rest.as_bytes();
        while close < bytes.len() && depth > 0 {
            match bytes[close] {
                b'{' => depth += 1,
                b'}' => depth -= 1,
                _ => {}
            }
            close += 1;
        }
        let body = &rest[open + 1..close.saturating_sub(1)];
        let declarations = body
            .split(';')
            .filter_map(|decl| decl.split_once(':'))
            .map(|(prop, value)| (prop.trim().to_string(), value.trim().to_string()))
            .filter(|(prop, _)| !prop.is_empty())
            .collect();
        blocks.push(Block {
            selector,
            declarations,
        });
        rest = &rest[close..];
    }
    blocks
}

fn strip_comments(css: &str) -> String {
    let mut out = String::with_capacity(css.len());
    let mut rest = css;
    while let Some(start) = rest.find("/*") {
        out.push_str(&rest[..start]);
        let end = rest[start..]
            .find("*/")
            .map(|i| start + i + 2)
            .unwrap_or(rest.len());
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

fn mode_values(css: &str, selector: &str) -> std::collections::HashMap<String, String> {
    let mut values = std::collections::HashMap::new();
    for block in parse_blocks(css) {
        if block.selector == selector {
            for (prop, value) in block.declarations {
                values.insert(prop, value);
            }
        }
    }
    values
}

#[test]
fn docs_theme_index_matches_the_bundled_set() {
    // docs/static/themes.json feeds the docs site's live theme gallery
    // (generated by scripts/gen-theme-index.mjs, run by build:docs).
    // It must list exactly what the binary embeds — a stale index ships
    // a stale gallery.
    let json = std::fs::read_to_string(repo("docs/static/themes.json"))
        .expect("docs/static/themes.json exists (run: node scripts/gen-theme-index.mjs)");
    let listed: Vec<serde_json::Value> = serde_json::from_str(&json).expect("a JSON array");
    let listed: Vec<String> = listed
        .iter()
        .map(|e| {
            e["name"]
                .as_str()
                .expect("each entry has a name")
                .to_string()
        })
        .collect();
    let bundled = rustpress::theme_assets::bundled_themes();
    assert_eq!(
        listed, bundled,
        "docs theme index drifted from vpkit's themes/"
    );

    // the gallery card data (blurb + both-mode mock tokens) must match
    // the theme files themselves, or the cards lie — regenerate with
    // `node scripts/gen-theme-index.mjs`
    for entry in listed {
        let css = read(&format!("node_modules/vpkit/themes/{entry}.css"));
        let item = serde_json::from_str::<Vec<serde_json::Value>>(&json)
            .unwrap()
            .into_iter()
            .find(|e| e["name"].as_str() == Some(entry.as_str()))
            .unwrap();
        assert!(
            !item["desc"].as_str().unwrap_or("").is_empty(),
            "theme {entry}: gallery blurb missing (header comment malformed?)"
        );
        for (mode, selector) in [("light", ":root"), ("dark", ".dark")] {
            let values = mode_values(&css, selector);
            let mock = item[mode]
                .as_object()
                .unwrap_or_else(|| panic!("theme {entry}: gallery {mode} mock tokens missing"));
            for (key, token) in [
                ("bg", "bg"),
                ("bgAlt", "bg-alt"),
                ("text", "text-1"),
                ("textMuted", "text-2"),
                ("border", "border"),
                ("brand", "brand-1"),
                ("success", "success-1"),
                ("warning", "warning-1"),
                ("danger", "danger-1"),
            ] {
                let want = values
                    .get(&format!("--vp-c-{token}"))
                    .unwrap_or_else(|| {
                        panic!("theme {entry}: --vp-c-{token} missing in {selector}")
                    })
                    .to_ascii_lowercase();
                let got = mock[key].as_str().unwrap_or("").to_ascii_lowercase();
                assert_eq!(
                    got, want,
                    "theme {entry}: {mode}.{key} drifted from vpkit's themes/{entry}.css"
                );
            }
        }
    }
}
