#!/usr/bin/env python3
"""Generate static/syntax.css from the giallo CSS Zola emits during build.

Zola (0.22+) writes public/giallo-light.css and public/giallo-dark.css when
[markdown.highlighting] uses style = "class" with a light/dark theme pair.
Both files use flat class selectors (z-l-* / z-d-*), which cannot be switched
with the `html.dark` class as-is. This script rewrites the dark theme rules so
they only apply under `html.dark`, producing one static/syntax.css that follows
the VitePress-style dark mode toggle.

Run after changing the highlighting themes in config.toml:

    zola build && python3 scripts/gen-syntax-css.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIGHT = ROOT / "public" / "giallo-light.css"
DARK = ROOT / "public" / "giallo-dark.css"
OUT = ROOT / "static" / "syntax.css"

RULE_RE = re.compile(r"([^{}]+)\{([^{}]*)\}")


def parse(css: str):
    """Yield (selectors, body) pairs, skipping comments."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    for selectors, body in RULE_RE.findall(css):
        yield selectors.strip(), body.strip()


def main() -> int:
    for p in (LIGHT, DARK):
        if not p.exists():
            print(f"error: {p} not found. Run `zola build` first.", file=sys.stderr)
            return 1

    lines = [
        "/* Generated by scripts/gen-syntax-css.py — do not edit by hand.",
        "   Regenerate with `zola build && python3 scripts/gen-syntax-css.py`. */",
        "",
    ]

    for selectors, body in parse(LIGHT.read_text()):
        lines.append(f"{selectors} {{\n  {body}\n}}\n")

    for selectors, body in parse(DARK.read_text()):
        scoped = ",\n".join(f"html.dark {s.strip()}" for s in selectors.split(","))
        lines.append(f"{scoped} {{\n  {body}\n}}\n")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines) - 4} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
